// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odonomics.Ledger;

#nullable disable

namespace Odonomics.Ledger.Migrations
{
    [DbContext(typeof(OdonomicsDbContext))]
    [Migration("20260925123353_AddPostingShippingFee")]
    partial class AddPostingShippingFee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Odonomics.Ledger.DealerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GradeCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "NormalizedLocation")
                        .IsUnique();

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("Odonomics.Ledger.LedgerMigrationEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("LedgerMigrations");
                });

            modelBuilder.Entity("Odonomics.Ledger.NoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleVin");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Odonomics.Ledger.PostingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleVin", "Source", "Url")
                        .IsUnique();

                    b.ToTable("Postings");
                });

            modelBuilder.Entity("Odonomics.Ledger.PriceObservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostingId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostingId");

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("Odonomics.Ledger.RunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RadiusMiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Odonomics.Ledger.VehicleEntity", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinalistMarkedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trim")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Vin");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Odonomics.Ledger.VinRecordEntity", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComplaintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComplaintsCouldNotFetchReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ComplaintsFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentListingDaysOnMarket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecodeRawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DecodedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryRawJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenRecallCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecallsCouldNotFetchReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RecallsFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecallsRawJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyCouldNotFetchReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SafetyFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafetyFrontRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SafetyOverallRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SafetyRawJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafetyRolloverRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SafetySideRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Vin");

                    b.ToTable("VinRecords");
                });

            modelBuilder.Entity("Odonomics.Ledger.NoteEntity", b =>
                {
                    b.HasOne("Odonomics.Ledger.VehicleEntity", "Vehicle")
                        .WithMany("Notes")
                        .HasForeignKey("VehicleVin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Odonomics.Ledger.PostingEntity", b =>
                {
                    b.HasOne("Odonomics.Ledger.DealerEntity", "Dealer")
                        .WithMany("Postings")
                        .HasForeignKey("DealerId");

                    b.HasOne("Odonomics.Ledger.VehicleEntity", "Vehicle")
                        .WithMany("Postings")
                        .HasForeignKey("VehicleVin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Odonomics.Ledger.PriceObservationEntity", b =>
                {
                    b.HasOne("Odonomics.Ledger.PostingEntity", "Posting")
                        .WithMany("PriceObservations")
                        .HasForeignKey("PostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posting");
                });

            modelBuilder.Entity("Odonomics.Ledger.VinRecordEntity", b =>
                {
                    b.HasOne("Odonomics.Ledger.VehicleEntity", "Vehicle")
                        .WithOne("VinRecord")
                        .HasForeignKey("Odonomics.Ledger.VinRecordEntity", "Vin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Odonomics.Ledger.DealerEntity", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("Odonomics.Ledger.PostingEntity", b =>
                {
                    b.Navigation("PriceObservations");
                });

            modelBuilder.Entity("Odonomics.Ledger.VehicleEntity", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Postings");

                    b.Navigation("VinRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
